- name: Create a jenkins job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'templates/pipeline.xml') }}"
    name: "test"
    token: "11add3fcc8500f08422cbd8cbc0f6a8bd4"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  loop:
    - {repoName: "cart" , componentName: "cart"}