- name: template
  template:
    src: pipeline.xml
    dest: /tmp/pipeline.xml
  loop:
    - {repoName: "cart" , componentName: "cart"}
    
- name: Create a jenkins job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'tmp/pipeline.xml') }}"
    name: "test"
    token: "11d887fd376447e3cbcae3fd930ef55fbf"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  