- name: templates
  template:
    src: pipeline.xml
    dest: /tmp/pipeline.xml
  loop:
    - {repoName: "cart" , componentName: "cart"}
- name: Create a jenkins pipeline
  community.general.jenkins_job:
    config: "{{ lookup('file', 'tmp/pipeline.xml') }}"
    name: "test"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
    token: "113137f3e38aa5f33a92e782ab524a114c"
