- name: Create a jenkins folder
  community.general.jenkins_job:
    config: "{{ lookup('template', 'folder.xml') }}"
    name: "{{item.Name}}"
    token: "11c3e5f43242ecdad44efc42abb23d27a3"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  loop: "{{folders}}"


- name: templates
  template:
    src: pipeline.xml
    dest: /tmp/pipeline.xml
- name: Create a jenkins pipeline job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    token: "11c3e5f43242ecdad44efc42abb23d27a3"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
  loop: "{{pipelineJobs}}"

#- name: Create a jenkins multibranch pipelines
#  community.general.jenkins_job:
#    config: "{{ lookup('template', 'multibranch.xml') }}"
#    name: "{{item.folderName}}{{item.jobName}}"
#    token: "11c3e5f43242ecdad44efc42abb23d27a3"
#    url: "http://jenkins.devopslearner.online:8080"
#    user: "admin"
#  loop: "{{multibranchJobs}}"
