  - name: Create a jenkins pipeline
  community.general.jenkins_job:
    config: "{{ lookup('template', '/tmp/pipeline.xml') }}"
    name: "test"
    url: "http://jenkins.devopslearner.online:8080"
    user: "admin"
    token: "113137f3e38aa5f33a92e782ab524a114c"
  loop:
    - {repoName: "cart" , componentName: "cart"}