- name: Create a jenkins folder
  community.general.jenkins_job:
    config: "{{ lookup('template', 'folder.xml') }}"
    name: "{{item.name}}"
    token: "11d887fd376447e3cbcae3fd930ef55fbf"
    url: "http://44.203.18.71:8080"
    user: "admin"
  loop: "{{folders}}"

- name: Create a jenkins job using the token
  community.general.jenkins_job:
    config: "{{ lookup('template', 'pipeline.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    token: "11d887fd376447e3cbcae3fd930ef55fbf"
    url: "http://44.203.18.71:8080"
    user: "admin"
  loop: "{{pipelineJobs}}"

- name: Create a jenkins multibranch pipelines
  community.general.jenkins_job:
    config: "{{ lookup('template', 'multibranch.xml') }}"
    name: "{{item.folderName}}{{item.jobName}}"
    token: "11d887fd376447e3cbcae3fd930ef55fbf"
    url: "http://44.203.18.71.online:8080"
    user: "admin"
  loop: "{{multibranchJobs}}"
  